### PR TITLE
Release 0.9.0

### PR DESCRIPTION
**Pull request by guilhem**

### CODE REVIEW

**Comment by jjasghar** [comment]
Seems reasonable :+1:

**Comment by tas50** [comment]
0.8.2 would be nice, but I think we actually have a 0.9.0 here since we've added a bunch of new functionality.

**Comment by guilhem** [comment]
Agreed with you @tas50 `civetweb` is enough to bump minor :)

**Comment by guilhem** [comment]
@cloudm2 please don't do some crapy stuff on this repository!

This PR have to be merged _after_ #211 (as said here https://github.com/ceph/ceph-cookbook/pull/211#issuecomment-140737631 ).
Release `0.9.0` (Commit 0ea7f15f20b34429daa326d25f4edf39ab6049a5 ) doesn't include good fixes from @tas50 .

**Comment by cloudm2** [comment]
Your stuff is just metadata stuff so push another one.

**Comment by cloudm2** [comment]
You should have retracted and reissued another PR if you want something in order.

**Comment by guilhem** [comment]
@cloudm2 that's why, IMHO, you can't be maintainer of this cookbook (but contributor absolutely).

Being maintainer require vision, communication and practice. You don't seems to have this 3.

With all this previous exchange, any Chef regular user will see what I'm talking about.
(By the way, I keep `just metadata` as a good Chef joke ;) )

**Comment by cloudm2** [comment]
It's unfortunate you feel this way. The repo will be making positive changes moving forward that will bring it up to speed (it's really far behind) and make it enterprise grade. I hope in the future you can contribute real code changes that help move this forward. As far as the supermarket is concerned, please keep it up to date with with the coming changes. Thanks.

**Pull request merged**
